name: DevSecOps CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # 1. SAST
    - name: Init CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: python

    - name: Run CodeQL
      uses: github/codeql-action/analyze@v3

    # 2. Sécurité Python
    - name: Install Bandit
      run: pip install bandit

    - name: Run Bandit
      run: bandit -r api --severity-level high

    # 3. Scan dépendances
    - name: Install Safety
      run: pip install safety

    - name: Dependency scan
      run: safety check -r requirements.txt

    # 4. Build Docker
    - name: Build image
      run: docker build -t devsecops-assignment .

    # 5. Scan image Docker
    - name: Trivy Scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: devsecops-assignment
        severity: CRITICAL,HIGH
        exit-code: 1
